<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getComments(string $postId) : array
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.postId = :postId')
            ->setParameter('postId', $postId)
            ->andWhere('c.replyTo = 0')
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function getSubComments(int $commentId) : array
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.replyTo = :commentId')
            ->setParameter('commentId', $commentId)
            ->getQuery();

        return $qb->getArrayResult();
    }
}
